# Generated by Django 3.0.5 on 2020-04-29 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_item_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='discoutn_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
