# Generated by Django 3.0.5 on 2020-04-29 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_item_discoutn_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='discoutn_price',
            new_name='discount_price',
        ),
    ]
