# Generated by Django 3.0.5 on 2020-04-29 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200429_0635'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='decription',
            field=models.TextField(default='This is a test description'),
            preserve_default=False,
        ),
    ]
