# Generated by Django 3.0.5 on 2020-05-02 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20200502_1629'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='stripe_charge',
            new_name='stripe_charge_id',
        ),
    ]
