# Generated by Django 3.0.5 on 2020-05-04 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_auto_20200504_1743'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='refound_granted',
            new_name='refund_granted',
        ),
    ]
